### ISSUE TITLE
Add items correctly to the cart

### ISSUE THREAD

**Issue by infinity-atom42** [Phantom-Tech-IND/school-pictures#72]
### Task: Add Product to Cart with Selected Images

- [ ] **Retrieve Product ID**
  - Ensure each product has a unique identifier.

- [ ] **Capture Selected Images**
  - Record the IDs of the images selected by the user:
    - [ ] Stickers
    - [ ] Portrait set
    - [ ] 18x24 Portrait

- [ ] **Determine Quantity**
  - Capture how many sets the user wants to purchase.

- [ ] **Include Additional Options**
  - Check for any additional options such as digital data:
    - [ ] Digital Data (+39 CHF)

- [ ] **Calculate Price and Total**
  - Compute the total cost based on the base price, selected options, and quantity.

- [ ] **Update Cart Backend**
  - Update the server or database with the new cart information.

- [ ] **Update Cart UI**
  - Refresh the cart display on the user interface to show the new item.

### Function Implementation (example in JavaScript)

```javascript
function addToCart(productId, imageSelections, quantity, options) {
    const cartItem = {
        productId: productId,
        images: {
            stickers: imageSelections.stickers,
            portraitSet: imageSelections.portraitSet,
            largePortrait: imageSelections.largePortrait
        },
        quantity: quantity,
        options: options,
        subtotal: calculateSubtotal(productId, quantity, options)
    };

    function calculateSubtotal(productId, quantity, options) {
        const basePrice = getProductPrice(productId);
        const optionsPrice = options.digitalData ? 39 : 0;
        return (basePrice + optionsPrice) * quantity;
    }

    shoppingCart.push(cartItem);
    updateCartDisplay();
}

const productId = "SparSet1";
const imageSelections = {
    stickers: "img123",
    portraitSet: "img234",
    largePortrait: "img345"
};
const quantity = 1;
const options = {
    digitalData: true
};

addToCart(productId, imageSelections, quantity, options);
