### ISSUE TITLE
Add SEO for the project

### ISSUE THREAD

**Issue by axentioialexandru95** [Phantom-Tech-IND/school-pictures#79]
### Task: Implement SEO Best Practices in a Laravel Application

- [x] Edit product page so that the details sit after the selectors

- [x] **XML Sitemap and Robots.txt**
  - Generate an XML sitemap and ensure it's updated regularly.
  - Configure `robots.txt` to manage crawler access.

- [x] **SEO Tools and Packages**
  - Consider using Laravel SEO packages such as `artesaos/seotools` or `spatie/laravel-seo-tools`.
  - Configure and utilize these tools to handle meta tags and SEO optimization tasks.

### Implementation Tips

- **Laravel Routing for SEO:**
  ```php
  Route::get('/{category}/{product_name}', function ($category, $productName) {
      return view('product', compact('category', 'productName'));
  })->name('product.detail');


<title>{{ $pageTitle }}</title>
<meta name="description" content="{{ $pageDescription }}">
